package compiler

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/nusapuksic/story/internal/ids"
	"github.com/nusapuksic/story/internal/project"
	storyprompts "github.com/nusapuksic/story/internal/prompts"
	"github.com/nusapuksic/story/internal/provider"
	"github.com/nusapuksic/story/internal/store"
)

const (
	characterIdentityTaskType      = "character-identities"
	characterIdentityRetryTaskType = "character-identities-retry"
	characterIdentityMaxAttempts   = 3
	CharacterVariantAlias          = "alias"
	CharacterVariantPossibleTypo   = "possible_typo"
	CharacterVariantNameChange     = "name_change"
	CharacterVariantUncertain      = "uncertain"
)

// CharacterIdentityRecord is a book-level identity grouping of canonical
// chapter-local character entities. IDs are generated by deterministic code.
type CharacterIdentityRecord struct {
	RecordType      string                      `json:"record_type"`
	CharacterID     string                      `json:"character_id"`
	SourceEntityIDs []string                    `json:"source_entity_ids"`
	CanonicalName   string                      `json:"canonical_name"`
	Aliases         []string                    `json:"aliases,omitempty"`
	Variants        []CharacterVariantRecord    `json:"variants,omitempty"`
	Generation      CharacterIdentityGeneration `json:"generation"`
	Status          string                      `json:"status"`
}

type CharacterVariantRecord struct {
	Type           string   `json:"type"`
	Value          string   `json:"value"`
	SourceEntityID string   `json:"source_entity_id,omitempty"`
	Evidence       []string `json:"evidence,omitempty"`
	Reason         string   `json:"reason,omitempty"`
}

type CharacterIdentityGeneration struct {
	RunID         string `json:"run_id"`
	Model         string `json:"model"`
	PromptVersion string `json:"prompt_version"`
	GeneratedAt   string `json:"generated_at"`
}

type CharacterIdentitiesSnapshotRecord struct {
	RecordType        string   `json:"record_type"`
	RunID             string   `json:"run_id"`
	IdentityCount     int      `json:"identity_count"`
	SourceEntityCount int      `json:"source_entity_count"`
	SourceEntityIDs   []string `json:"source_entity_ids"`
	InputHash         string   `json:"input_hash"`
	ArtifactHash      string   `json:"artifact_hash"`
	Model             string   `json:"model"`
	PromptVersion     string   `json:"prompt_version"`
	CommittedAt       string   `json:"committed_at"`
}

type rawCharacterIdentityResponse struct {
	Characters []rawCharacterIdentity `json:"characters"`
	Identities []rawCharacterIdentity `json:"identities"`
}
type rawCharacterIdentity struct {
	SourceEntityIDs flexibleStringList    `json:"source_entity_ids"`
	EntityIDs       flexibleStringList    `json:"entity_ids"`
	CanonicalName   flexibleString        `json:"canonical_name"`
	Aliases         flexibleStringList    `json:"aliases"`
	Variants        []rawCharacterVariant `json:"variants"`
}
type rawCharacterVariant struct {
	Type           flexibleString     `json:"type"`
	Value          flexibleString     `json:"value"`
	SurfaceText    flexibleString     `json:"surface_text"`
	SourceEntityID flexibleString     `json:"source_entity_id"`
	EntityID       flexibleString     `json:"entity_id"`
	Evidence       flexibleStringList `json:"evidence"`
	EvidenceIDs    flexibleStringList `json:"evidence_ids"`
	Reason         flexibleString     `json:"reason"`
}

type characterIdentitySource struct {
	EntityID       string   `json:"entity_id"`
	ChapterID      string   `json:"chapter_id"`
	CanonicalName  string   `json:"canonical_name"`
	Aliases        []string `json:"aliases,omitempty"`
	EvidenceScenes []string `json:"evidence_scenes"`
	SurfaceTexts   []string `json:"surface_texts,omitempty"`
}
type characterIdentityScene struct {
	SceneID      string   `json:"scene_id"`
	ChapterID    string   `json:"chapter_id"`
	Summary      string   `json:"summary,omitempty"`
	Participants []string `json:"participants,omitempty"`
	POV          []string `json:"pov,omitempty"`
}
type characterIdentityInput struct {
	SourceEntities []characterIdentitySource          `json:"source_entities"`
	SceneCards     []characterIdentityScene           `json:"scene_cards"`
	InputHash      string                             `json:"-"`
	EntityByID     map[string]characterIdentitySource `json:"-"`
	SceneIDs       map[string]bool                    `json:"-"`
	ScenesByEntity map[string]map[string]bool         `json:"-"`
}
type stagedCharacterIdentitiesPayload struct {
	Records  []CharacterIdentityRecord         `json:"records"`
	Snapshot CharacterIdentitiesSnapshotRecord `json:"snapshot"`
}

func compileCharacterIdentities(ctx context.Context, p *project.Project, st *store.Store, chapters []store.ChapterRow, opts Options, cfg sceneDetectConfig, run *Run) (int, error) {
	if strings.TrimSpace(opts.ChapterID) != "" {
		return 0, fmt.Errorf("character-identities is a book-level compile layer; --chapter is not supported")
	}
	if err := ensureEntitySnapshotsCommitted(st, chapters); err != nil {
		return 0, err
	}
	input, err := buildCharacterIdentityInput(st)
	if err != nil {
		return 0, err
	}
	path := p.Path(filepath.Join(project.ModelDir, "character_identities.jsonl"))
	current, currentSnapshot, err := ReadLatestCharacterIdentities(path)
	if err != nil {
		return 0, err
	}
	prompt := loadCompilerPrompt(p, storyprompts.CharacterIdentities)
	if !opts.Force && characterIdentitiesSnapshotIsCurrent(currentSnapshot, input.InputHash, opts.ExtractionModel, prompt.Version) {
		reportProgress(opts, ProgressEvent{Layer: LayerCharacterIdentities, Stage: "item-skip", Message: "Character identities: already current"})
		return 0, nil
	}
	generation := CharacterIdentityGeneration{RunID: runID(run), Model: opts.ExtractionModel, PromptVersion: prompt.Version, GeneratedAt: time.Now().UTC().Format(time.RFC3339)}
	records := []CharacterIdentityRecord{}
	if len(input.SourceEntities) > 0 {
		if opts.ExtractionProvider == nil {
			return 0, errors.New("no LLM provider configured: character identities require an extraction provider; configure [llm] in story.toml")
		}
		reportProgress(opts, ProgressEvent{Layer: LayerCharacterIdentities, Stage: "item-start", Message: fmt.Sprintf("Character identities: resolving %d character entities", len(input.SourceEntities))})
		records, err = extractCharacterIdentities(ctx, p, input, current, opts.ExtractionProvider, opts.ExtractionModel, cfg, prompt, generation, run, opts.Progress)
		if err != nil {
			return 0, err
		}
	}
	sort.SliceStable(records, func(i, j int) bool { return records[i].CharacterID < records[j].CharacterID })
	artifactHash, err := hashCharacterIdentityRecords(records)
	if err != nil {
		return 0, err
	}
	sourceIDs := make([]string, 0, len(input.SourceEntities))
	for _, e := range input.SourceEntities {
		sourceIDs = append(sourceIDs, e.EntityID)
	}
	sort.Strings(sourceIDs)
	snapshot := CharacterIdentitiesSnapshotRecord{RecordType: "character_identities_snapshot", RunID: runID(run), IdentityCount: len(records), SourceEntityCount: len(sourceIDs), SourceEntityIDs: sourceIDs, InputHash: input.InputHash, ArtifactHash: artifactHash, Model: opts.ExtractionModel, PromptVersion: prompt.Version, CommittedAt: time.Now().UTC().Format(time.RFC3339)}
	staging, err := optionalRunStagingStore(run)
	if err != nil {
		return 0, err
	}
	var staged StagedResultRef
	if staging != nil {
		staged, err = staging.StageJSON(LayerCharacterIdentities, StagedResultMeta{Sequence: 0, TaskID: "character-identities", TargetID: "book", TargetHash: input.InputHash, SchemaVersion: 1}, stagedCharacterIdentitiesPayload{Records: records, Snapshot: snapshot})
		if err != nil {
			return 0, err
		}
	}
	if err := commitCharacterIdentities(path, records, snapshot); err != nil {
		return 0, err
	}
	if staging != nil {
		if err := staging.RecordCommit(staged); err != nil {
			return 0, err
		}
	}
	reportProgress(opts, ProgressEvent{Layer: LayerCharacterIdentities, Stage: "item-complete", Message: fmt.Sprintf("Character identities: committed %d identity record(s)", len(records))})
	return len(records), nil
}

func buildCharacterIdentityInput(st *store.Store) (characterIdentityInput, error) {
	rows, err := st.EntityRowsForChapter("")
	if err != nil {
		return characterIdentityInput{}, err
	}
	scenes, err := st.AllScenes()
	if err != nil {
		return characterIdentityInput{}, err
	}
	cards, err := st.AllSceneCards()
	if err != nil {
		return characterIdentityInput{}, err
	}
	sceneChapter := map[string]string{}
	for _, s := range scenes {
		sceneChapter[s.ID] = s.ChapterID
	}
	input := characterIdentityInput{EntityByID: map[string]characterIdentitySource{}, SceneIDs: map[string]bool{}, ScenesByEntity: map[string]map[string]bool{}}
	for _, s := range scenes {
		input.SceneIDs[s.ID] = true
	}
	cardsByID := map[string]store.SceneCardRow{}
	for _, c := range cards {
		cardsByID[c.SceneID] = c
	}
	for _, row := range rows {
		if !strings.EqualFold(strings.TrimSpace(row.Type), "character") {
			continue
		}
		e := characterIdentitySource{EntityID: row.ID, ChapterID: row.ChapterID, CanonicalName: strings.TrimSpace(row.CanonicalName), Aliases: sortedCleanStrings(row.Aliases)}
		occs, err := st.OccurrencesForEntity(row.ID, "", 100000)
		if err != nil {
			return characterIdentityInput{}, err
		}
		for _, occ := range occs {
			if occ.SceneID != "" {
				e.EvidenceScenes = append(e.EvidenceScenes, occ.SceneID)
				e.SurfaceTexts = append(e.SurfaceTexts, occ.SurfaceTexts...)
			}
		}
		e.EvidenceScenes = sortedCleanStrings(e.EvidenceScenes)
		e.SurfaceTexts = dedupeStrings(e.SurfaceTexts)
		input.SourceEntities = append(input.SourceEntities, e)
		input.EntityByID[e.EntityID] = e
		input.ScenesByEntity[e.EntityID] = map[string]bool{}
		for _, sid := range e.EvidenceScenes {
			input.ScenesByEntity[e.EntityID][sid] = true
		}
	}
	sort.SliceStable(input.SourceEntities, func(i, j int) bool { return input.SourceEntities[i].EntityID < input.SourceEntities[j].EntityID })
	for _, c := range cards {
		var raw struct {
			Participants []string `json:"participants"`
			POV          []string `json:"pov"`
		}
		_ = json.Unmarshal([]byte(c.RawJSON), &raw)
		input.SceneCards = append(input.SceneCards, characterIdentityScene{SceneID: c.SceneID, ChapterID: sceneChapter[c.SceneID], Summary: stripParagraphRefs(c.Summary), Participants: dedupeStrings(raw.Participants), POV: dedupeStrings(raw.POV)})
	}
	data, err := json.Marshal(struct {
		SourceEntities []characterIdentitySource `json:"source_entities"`
		SceneCards     []characterIdentityScene  `json:"scene_cards"`
	}{input.SourceEntities, input.SceneCards})
	if err != nil {
		return characterIdentityInput{}, err
	}
	input.InputHash = "sha256:" + sha256Hex(data)
	return input, nil
}

func extractCharacterIdentities(ctx context.Context, p *project.Project, input characterIdentityInput, current []CharacterIdentityRecord, prov provider.Provider, model string, cfg sceneDetectConfig, loaded storyprompts.Loaded, generation CharacterIdentityGeneration, run *Run, progress ProgressFunc) ([]CharacterIdentityRecord, error) {
	base := []provider.Message{{Role: "system", Content: loaded.Content}, {Role: "user", Content: buildCharacterIdentityPrompt(input)}}
	var last error
	for attempt := 1; attempt <= characterIdentityMaxAttempts; attempt++ {
		taskID := ids.NewTaskID()
		messages := append([]provider.Message(nil), base...)
		if last != nil {
			emitProgress(progress, ProgressEvent{Layer: LayerCharacterIdentities, Stage: "item-retry", Current: attempt, Total: characterIdentityMaxAttempts, Message: fmt.Sprintf("Character identities: retrying invalid model output (attempt %d/%d): %s", attempt, characterIdentityMaxAttempts, compactProgressError(last))})
			messages = append(messages, provider.Message{Role: "user", Content: buildCharacterIdentityRetryPrompt()})
		}
		resp, timing, err := generateWithAudit(ctx, run, taskID, prov, provider.GenerationRequest{Model: model, Messages: messages, Temperature: cfg.Temperature, MaxTokens: cfg.MaxOutputTokens, JSONMode: true})
		taskType := characterIdentityTaskType
		if attempt > 1 {
			taskType = characterIdentityRetryTaskType
		}
		if err != nil {
			recordCharacterIdentityTask(run, taskID, taskType, TaskStatusFailed, loaded.Version, err.Error(), timing)
			return nil, fmt.Errorf("character identity LLM call: %w", err)
		}
		records, parseErr := parseCharacterIdentityResponse(resp.Content, input, current, generation)
		status := TaskStatusCompleted
		msg := ""
		if parseErr != nil {
			status = TaskStatusFailed
			msg = parseErr.Error()
		}
		recordCharacterIdentityTask(run, taskID, taskType, status, loaded.Version, msg, timing)
		if parseErr == nil {
			return records, nil
		}
		last = parseErr
	}
	return nil, fmt.Errorf("character identity output: failed after %d attempts: %w", characterIdentityMaxAttempts, last)
}

func buildCharacterIdentityPrompt(input characterIdentityInput) string {
	var b strings.Builder
	b.WriteString("Resolve book-level character identities as JSON.\n")
	b.WriteString("Group only supplied character entity IDs; do not invent IDs or regroup scene evidence. Return each source_entity_id exactly once.\n")
	b.WriteString(`{"characters":[{"source_entity_ids":["entity-..."],"canonical_name":"...","aliases":[],"variants":[{"type":"alias|possible_typo|name_change|uncertain","value":"...","source_entity_id":"entity-...","evidence":["sc-..."],"reason":"..."}]}]}`)
	b.WriteString("\nCanonical names and aliases must be copied from the supplied entity records. Preserve questionable merges with an uncertain variant or separate groups.\n\nEntities:\n")
	for _, e := range input.SourceEntities {
		fmt.Fprintf(&b, "- entity_id: %s; chapter: %s; canonical_name: %s; aliases: %s; allowed_scene_ids: %s; surface_texts: %s\n", e.EntityID, e.ChapterID, e.CanonicalName, strings.Join(e.Aliases, "; "), strings.Join(e.EvidenceScenes, ", "), strings.Join(e.SurfaceTexts, "; "))
	}
	b.WriteString("\nLinked scene-card evidence:\n")
	for _, c := range input.SceneCards {
		fmt.Fprintf(&b, "- %s (%s) summary: %s; participants: %s; pov: %s\n", c.SceneID, c.ChapterID, c.Summary, strings.Join(c.Participants, "; "), strings.Join(c.POV, "; "))
	}
	return b.String()
}
func buildCharacterIdentityRetryPrompt() string {
	return "Previous response failed validation. Return a complete replacement JSON object, not a patch. Use only the supplied source_entity_ids, canonical names, aliases, and allowed scene IDs. Every source_entity_id must appear exactly once."
}

func parseCharacterIdentityResponse(content string, input characterIdentityInput, current []CharacterIdentityRecord, generation CharacterIdentityGeneration) ([]CharacterIdentityRecord, error) {
	content = stripJSONFences(content)
	var raw rawCharacterIdentityResponse
	if err := json.Unmarshal([]byte(content), &raw); err != nil {
		return nil, fmt.Errorf("parse character identity response: %w", err)
	}
	values := raw.Characters
	if len(values) == 0 {
		values = raw.Identities
	}
	if len(values) == 0 {
		return nil, fmt.Errorf("response contains no character identity records")
	}
	seen := map[string]bool{}
	records := make([]CharacterIdentityRecord, 0, len(values))
	for _, v := range values {
		idsRaw := append([]string{}, []string(v.SourceEntityIDs)...)
		idsRaw = append(idsRaw, []string(v.EntityIDs)...)
		if len(idsRaw) == 0 {
			return nil, fmt.Errorf("character identity missing source_entity_ids")
		}
		local := map[string]bool{}
		for _, id := range idsRaw {
			id = strings.TrimSpace(id)
			if id == "" {
				return nil, fmt.Errorf("character identity contains empty source_entity_id")
			}
			if local[id] {
				return nil, fmt.Errorf("source_entity_id %q appears more than once in character identity", id)
			}
			local[id] = true
			if seen[id] {
				return nil, fmt.Errorf("source_entity_id %q appears in more than one character identity", id)
			}
			e, ok := input.EntityByID[id]
			if !ok {
				return nil, fmt.Errorf("character identity references unknown source_entity_id %q", id)
			}
			seen[id] = true
			_ = e
		}
		sourceIDs := sortedCleanStrings(idsRaw)
		entities := make([]characterIdentitySource, 0, len(sourceIDs))
		for _, id := range sourceIDs {
			entities = append(entities, input.EntityByID[id])
		}
		name := strings.TrimSpace(string(v.CanonicalName))
		if name == "" {
			name = entities[0].CanonicalName
		}
		if !characterNameAllowed(name, entities) {
			return nil, fmt.Errorf("character identity canonical_name %q is not supplied by source entities", name)
		}
		aliases := []string{}
		for _, a := range []string(v.Aliases) {
			a = strings.TrimSpace(a)
			if a == "" {
				continue
			}
			if !characterNameAllowed(a, entities) {
				return nil, fmt.Errorf("character identity alias %q is not supplied by source entities", a)
			}
			if !strings.EqualFold(a, name) {
				aliases = append(aliases, a)
			}
		}
		for _, entity := range entities {
			if !strings.EqualFold(entity.CanonicalName, name) {
				aliases = append(aliases, entity.CanonicalName)
			}
			aliases = append(aliases, entity.Aliases...)
		}
		variants, err := characterVariantsFromRaw(v.Variants, entities, input)
		if err != nil {
			return nil, err
		}
		records = append(records, CharacterIdentityRecord{RecordType: "character_identity", CharacterID: existingCharacterIdentityID(current, sourceIDs), SourceEntityIDs: sourceIDs, CanonicalName: chooseIdentityName(name, entities), Aliases: dedupeStrings(aliases), Variants: variants, Generation: generation, Status: "generated"})
	}
	if len(seen) != len(input.SourceEntities) {
		missing := []string{}
		for _, e := range input.SourceEntities {
			if !seen[e.EntityID] {
				missing = append(missing, e.EntityID)
			}
		}
		return nil, fmt.Errorf("character identity response omitted source_entity_id(s): %s", strings.Join(missing, ", "))
	}
	sort.SliceStable(records, func(i, j int) bool { return records[i].CharacterID < records[j].CharacterID })
	return records, nil
}
func characterNameAllowed(name string, entities []characterIdentitySource) bool {
	for _, e := range entities {
		if strings.EqualFold(name, e.CanonicalName) {
			return true
		}
		for _, a := range e.Aliases {
			if strings.EqualFold(name, a) {
				return true
			}
		}
	}
	return false
}
func chooseIdentityName(name string, entities []characterIdentitySource) string {
	for _, e := range entities {
		if strings.EqualFold(name, e.CanonicalName) {
			return e.CanonicalName
		}
	}
	for _, e := range entities {
		for _, a := range e.Aliases {
			if strings.EqualFold(name, a) {
				return a
			}
		}
	}
	return entities[0].CanonicalName
}
func characterVariantsFromRaw(raw []rawCharacterVariant, entities []characterIdentitySource, input characterIdentityInput) ([]CharacterVariantRecord, error) {
	allowedEntity := map[string]bool{}
	allowedValue := map[string]bool{}
	for _, e := range entities {
		allowedEntity[e.EntityID] = true
		allowedValue[strings.ToLower(e.CanonicalName)] = true
		for _, a := range e.Aliases {
			allowedValue[strings.ToLower(a)] = true
		}
		for _, s := range e.SurfaceTexts {
			allowedValue[strings.ToLower(s)] = true
		}
	}
	out := []CharacterVariantRecord{}
	for _, v := range raw {
		typ := strings.ToLower(strings.TrimSpace(string(v.Type)))
		typ = strings.ReplaceAll(typ, "-", "_")
		switch typ {
		case CharacterVariantAlias, CharacterVariantPossibleTypo, CharacterVariantNameChange, CharacterVariantUncertain:
		default:
			return nil, fmt.Errorf("unsupported character variant type %q", string(v.Type))
		}
		value := strings.TrimSpace(string(v.Value))
		if value == "" {
			value = strings.TrimSpace(string(v.SurfaceText))
		}
		if value == "" || !allowedValue[strings.ToLower(value)] {
			return nil, fmt.Errorf("character variant value %q is not supplied evidence", value)
		}
		source := strings.TrimSpace(string(v.SourceEntityID))
		if source == "" {
			source = strings.TrimSpace(string(v.EntityID))
		}
		if source != "" && !allowedEntity[source] {
			return nil, fmt.Errorf("character variant references unknown source_entity_id %q", source)
		}
		evidence := sortedCleanStrings(append([]string{}, []string(v.Evidence)...))
		evidence = sortedCleanStrings(append(evidence, []string(v.EvidenceIDs)...))
		for _, sid := range evidence {
			if !input.SceneIDs[sid] {
				return nil, fmt.Errorf("character variant references unknown evidence_id %q", sid)
			}
			if source != "" && !input.ScenesByEntity[source][sid] {
				return nil, fmt.Errorf("character variant evidence scene %q is not linked to source entity %q", sid, source)
			}
		}
		out = append(out, CharacterVariantRecord{Type: typ, Value: value, SourceEntityID: source, Evidence: evidence, Reason: strings.TrimSpace(string(v.Reason))})
	}
	return out, nil
}

func existingCharacterIdentityID(records []CharacterIdentityRecord, sourceIDs []string) string {
	key := characterRoleSourceKey(sourceIDs)
	for _, record := range records {
		if characterRoleSourceKey(record.SourceEntityIDs) == key && strings.TrimSpace(record.CharacterID) != "" {
			return record.CharacterID
		}
	}
	return ids.NewCharacterID()
}

func hashCharacterIdentityRecords(records []CharacterIdentityRecord) (string, error) {
	b, err := json.Marshal(records)
	if err != nil {
		return "", err
	}
	return "sha256:" + sha256Hex(b), nil
}
func characterIdentitiesSnapshotIsCurrent(s *CharacterIdentitiesSnapshotRecord, inputHash, model, prompt string) bool {
	return s != nil && s.InputHash == inputHash && s.Model == model && s.PromptVersion == prompt && s.ArtifactHash != ""
}
func commitCharacterIdentities(path string, records []CharacterIdentityRecord, snapshot CharacterIdentitiesSnapshotRecord) error {
	f, err := openAppendJSONL(path)
	if err != nil {
		return err
	}
	defer f.Close()
	items := make([]any, 0, len(records)+1)
	for _, r := range records {
		items = append(items, r)
	}
	items = append(items, snapshot)
	return appendJSONLBatch(f, items)
}
func ReadLatestCharacterIdentities(path string) ([]CharacterIdentityRecord, *CharacterIdentitiesSnapshotRecord, error) {
	f, err := os.Open(path)
	if errors.Is(err, os.ErrNotExist) {
		return nil, nil, nil
	}
	if err != nil {
		return nil, nil, fmt.Errorf("read character identities: %w", err)
	}
	defer f.Close()
	var pending, latest []CharacterIdentityRecord
	var snapOut *CharacterIdentitiesSnapshotRecord
	sc := bufioScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" {
			continue
		}
		var typ struct {
			RecordType string `json:"record_type"`
		}
		if err := json.Unmarshal([]byte(line), &typ); err != nil {
			return nil, nil, fmt.Errorf("read character identities: malformed json: %w", err)
		}
		switch typ.RecordType {
		case "character_identity":
			var r CharacterIdentityRecord
			if err := json.Unmarshal([]byte(line), &r); err != nil {
				return nil, nil, err
			}
			pending = append(pending, r)
		case "character_identities_snapshot":
			var s CharacterIdentitiesSnapshotRecord
			if err := json.Unmarshal([]byte(line), &s); err != nil {
				return nil, nil, err
			}
			if s.IdentityCount != len(pending) {
				return nil, nil, fmt.Errorf("read character identities: snapshot identity_count mismatch: declared %d, pending %d", s.IdentityCount, len(pending))
			}
			latest = append([]CharacterIdentityRecord(nil), pending...)
			cp := s
			snapOut = &cp
			pending = nil
		}
	}
	if err := sc.Err(); err != nil {
		return nil, nil, err
	}
	return latest, snapOut, nil
}
func recordCharacterIdentityTask(run *Run, taskID, taskType, status, promptVersion, errMsg string, timings ...taskTiming) {
	if run == nil {
		return
	}
	r := TaskRecord{TaskID: taskID, RunID: runID(run), TaskType: taskType, Status: status, PromptVersion: promptVersion, Error: errMsg}
	if len(timings) > 0 {
		timings[0].applyTo(&r)
	}
	_ = run.recordTask(r)
}
